### ISSUE TITLE
내 정보 조회 시 비밀번호 확인 기능 추가 요청

### ISSUE THREAD

**Issue by HG-KR98** [TEAM-2NE1/steach-server#91]
# 기능 개선 리포트

## 필요한 기능이 현재 사용하는데 문제가 있는지 알려주세요
> 어떤 기능을 사용할 때 문제가 있는지 자세히 알려주세요.  
> ex) 재현 방법
> 1.
> 2.

1. 내 정보 수정 탭으로 들어가서 비밀번호를 확인할 때 비밀번호에 대한 정보 저장을 해놓은 상태가 아니므로 비밀번호를 확인할 수 있는 기능이 필요합니다.

<br><br>
## 어떻게 개선되었으면 좋을지 설명해주세요.
> 원하는 방식에 대한 자세한 설명이 필요합니다.

- 비밀번호를 입력하였을 때 post api 요청을 통하여 비밀번호를 보냈을 때 서버에서 확인 후 그 유저에 대한 정보들을 주는 방식을 원합니다. 토큰도 담아서 보내면 더 좋을 것 같습니다.

<br><br>
## 대안이 있다면 알려주세요.
> 대안으로 생각하는 해결 방법이나 기능을 적어주세요. 👍

<br><br>
## 참고할만한 자료가 있을까요?
> 참고자료가 있다면 첨부해주세요. 👍

<br><br><br><br><br>
<hr>

**Comment by Juhyorim** [comment]
`/api/v1/check/password` 라는 임시토큰을 발급받는 API를 만들었습니다!
토큰 유효기간은 60분이며, 회원(강사, 학생) 정보 수정 API 호출 시 필수로 넣어줘야합니다. `password_auth_token`

**Comment by sihyunjojo** [comment]
해결 된걸로 보입니다.
